DROP TABLE BOOKING;
DROP TABLE BOOKINGRECORD;
DROP TABLE MANAGER;
DROP TABLE ROOMTYPE;
DROP TABLE ROOM;
DROP TABLE HOTELUSER;


CREATE TABLE BOOKING (
	ID INTEGER NOT NULL PRIMARY KEY,
	CLIENTID	INTEGER NOT NULL,
	STARTDATE		DATE NOT NULL,
	ENDDATE		DATE NOT NULL,
	PIN			VARCHAR(10) NOT NULL
);

CREATE TABLE BOOKINGRECORD (
	ID INTEGER NOT NULL PRIMARY KEY,
	BOOKINGID	INTEGER,
	ROOMTYPE	VARCHAR2(100),	
	EXTRABED	CHAR(2) DEFAULT 'N',
	ROOM		INTEGER,
	ROOMNUMBER INTEGER,
	STARTDATE DATE NOT NULL,
	ENDDATE DATE NOT null,
	PRICE		DECIMAL NOT NULL
);

CREATE TABLE MANAGER (
	ID INTEGER NOT NULL PRIMARY KEY,
	USERNAME	VARCHAR2(100) NOT NULL,
	PASSWORD	VARCHAR2(50) NOT NULL
);

CREATE TABLE ROOMTYPE (
  ID INTEGER PRIMARY KEY NOT NULL,
	DESCRIPTION VARCHAR2(100),
	NUMPEOPLE	INTEGER NOT NULL,
  EXTRABED	CHAR(2) DEFAULT 'N',
	PRICERATE	DECIMAL NOT NULL
);

CREATE TABLE ROOM (
	ID INTEGER PRIMARY KEY NOT NULL,
	ROOMNUM		INTEGER,
	TYPE		INTEGER NOT NULL,
	STATUS	INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE "USER" (
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	PHONENUM	INTEGER,
	EMAIL		VARCHAR(100) NOT NULL,
  STATUS INTEGER DEFAULT 1
);

INSERT INTO "USER" (ID,NAME,ADDRESS,PHONENUM,EMAIL) VALUES (1,'John','1 Anzac Pde., NSW 2035',040111111,'john@gmail.com');
INSERT INTO "USER" (ID,NAME,ADDRESS,PHONENUM,EMAIL) VALUES (2,'Mary','2 Anzac Pde., NSW 2035',0401111112,'mary@gmail.com');
INSERT INTO "USER" (ID,NAME,ADDRESS,PHONENUM,EMAIL) VALUES (3,'Eric','3 Anzac Pde., NSW 2035',040111113,'eric@gmail.com');
INSERT INTO "USER" (ID,NAME,ADDRESS,PHONENUM,EMAIL,STATUS) VALUES (4,'ADMIN','ADMIN LOCATION',111111111,'admin@gmail.com',2);

INSERT INTO ROOMTYPE VALUES (1,'Single Room (with 1 single bed)',1,'N',70);
INSERT INTO ROOMTYPE VALUES (2,'Twin Bed (2 single beds)',2,'Y',120);
INSERT INTO ROOMTYPE VALUES (3,'Queen (1 double bed)',2,'Y',160);
INSERT INTO ROOMTYPE VALUES (4,'Executive (1 double bed, more facilities than Queen)',2,'Y',200);
INSERT INTO ROOMTYPE VALUES (5,'Suite (2 double beds, most luxurious)',4,'Y',400);

INSERT INTO ROOM VALUES (1,111,1,0);
INSERT INTO ROOM VALUES (2,112,2,0);
INSERT INTO ROOM VALUES (3,113,2,0);
INSERT INTO ROOM VALUES (4,214,3,0);
INSERT INTO ROOM VALUES (5,215,4,0);
INSERT INTO ROOM VALUES (6,216,5,0);
INSERT INTO ROOM VALUES (7,311,1,0);
INSERT INTO ROOM VALUES (8,312,2,0);
INSERT INTO ROOM VALUES (9,313,2,0);
INSERT INTO ROOM VALUES (10,314,3,0);
INSERT INTO ROOM VALUES (11,411,4,0);
INSERT INTO ROOM VALUES (12,412,5,0);
commit;
/*================================USE THESE BELOW======================================*/
CREATE TABLE HOTELROOM (
	ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	ROOMNUM		VARCHAR2(10),
	TYPE		VARCHAR2(10) NOT NULL,
	STATUS	CHAR(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOTELBOOKING (
	ID VARCHAR2(10) NOT NULL PRIMARY KEY,
	CLIENTID	VARCHAR2(10) NOT NULL,
	STARTDATE		DATE NOT NULL,
	ENDDATE		DATE NOT NULL,
	PIN			VARCHAR2(10) NOT NULL
);

CREATE TABLE HOTELBOOKINGRECORD (
	ID VARCHAR2(5) NOT NULL PRIMARY KEY,
	BOOKINGID	VARCHAR2(10),
	ROOMTYPE	VARCHAR2(100),	
	EXTRABED	CHAR(2) DEFAULT 'N',
	ROOM		VARCHAR2(10),
	ROOMNUMBER VARCHAR2(10),
	STARTDATE DATE NOT NULL,
	ENDDATE DATE NOT NULL,
	PRICE		DECIMAL NOT NULL
);

CREATE TABLE HOTELMANAGER (
	ID VARCHAR2(5) NOT NULL PRIMARY KEY,
	USERNAME	VARCHAR2(100) NOT NULL,
	PASSWORD	VARCHAR2(50) NOT NULL
);

CREATE TABLE HOTELROOMTYPE (
  ID VARCHAR2(5) PRIMARY KEY NOT NULL,
	DESCRIPTION VARCHAR2(100),
	NUMPEOPLE	VARCHAR2(5) NOT NULL,
  EXTRABED	CHAR(2) DEFAULT 'N',
	PRICERATE	DECIMAL NOT NULL
);

CREATE TABLE HOTELUSER (
	ID VARCHAR2(5) PRIMARY KEY NOT NULL,
	USERNAME VARCHAR2(100) NOT NULL,
	PASSWORD	VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(100),
	PHONENUM	VARCHAR2(100),
	EMAIL		VARCHAR2(100) NOT NULL,
  STATUS CHAR(1) DEFAULT 1
);


INSERT INTO HOTELUSER (ID,USERNAME,PASSWORD,ADDRESS,PHONENUM,EMAIL) VALUES (1,'John','123','1 Anzac Pde., NSW 2035',040111111,'john@gmail.com');
INSERT INTO HOTELUSER (ID,USERNAME,PASSWORD,ADDRESS,PHONENUM,EMAIL) VALUES (2,'Mary','123','2 Anzac Pde., NSW 2035',0401111112,'mary@gmail.com');
INSERT INTO HOTELUSER (ID,USERNAME,PASSWORD,ADDRESS,PHONENUM,EMAIL) VALUES (3,'Eric','123','3 Anzac Pde., NSW 2035',040111113,'eric@gmail.com');
INSERT INTO HOTELUSER (ID,USERNAME,PASSWORD,ADDRESS,PHONENUM,EMAIL,STATUS) VALUES (4,'admin','123','ADMIN LOCATION',111111111,'admin@gmail.com',2);
COMMIT;

INSERT INTO HOTELROOMTYPE VALUES (1,'Single Room (with 1 single bed)',1,'N',70);
INSERT INTO HOTELROOMTYPE VALUES (2,'Twin Bed (2 single beds)',2,'Y',120);
INSERT INTO HOTELROOMTYPE VALUES (3,'Queen (1 double bed)',2,'Y',160);
INSERT INTO HOTELROOMTYPE VALUES (4,'Executive (1 double bed, more facilities than Queen)',2,'Y',200);
INSERT INTO HOTELROOMTYPE VALUES (5,'Suite (2 double beds, most luxurious)',4,'Y',400);
COMMIT;

INSERT INTO HOTELROOM VALUES (1,111,1,0);
INSERT INTO HOTELROOM VALUES (2,112,2,0);
INSERT INTO HOTELROOM VALUES (3,113,2,0);
INSERT INTO HOTELROOM VALUES (4,214,3,0);
INSERT INTO HOTELROOM VALUES (5,215,4,0);
INSERT INTO HOTELROOM VALUES (6,216,5,0);
INSERT INTO HOTELROOM VALUES (7,311,1,0);
INSERT INTO HOTELROOM VALUES (8,312,2,0);
INSERT INTO HOTELROOM VALUES (9,313,2,0);
INSERT INTO HOTELROOM VALUES (10,314,3,0);
INSERT INTO HOTELROOM VALUES (11,411,4,0);
INSERT INTO HOTELROOM VALUES (12,412,5,0);
COMMIT;
